# Generated by Django 4.1.3 on 2022-11-09 09:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_feature_productthum_product_price_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='specifecations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], null=True, size=None),
        ),
    ]
