# Generated by Django 4.1.3 on 2022-11-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_information_specifecations_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='product_suggestion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='suggestion',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='ProductThum',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
