# Generated by Django 4.1.3 on 2022-11-12 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_information_productthum_suggestion_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_field', to='product.information'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_field', to='product.product'),
        ),
    ]
