# Generated by Django 4.1.3 on 2022-11-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_feature_information_alter_suggestion_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='information_field', to='product.product'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='category',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='product_suggestion',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_field', to='product.productthum'),
        ),
    ]
