# Generated by Django 4.1.3 on 2022-11-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_description_product_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productthum',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
