# Generated by Django 4.1.3 on 2022-11-13 08:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='specifecations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='category',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
