# Generated by Django 4.1.3 on 2022-11-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_information_specifecations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productthum',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productthum',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
